### ISSUE TITLE
misc: project smell tracker

### ISSUE THREAD

**Issue by NiceAesth** [osuAkatsuki/bancho.py#494]
- [x] Databases pinned to ancient version
- [x] Redis library out of date
- [x] Scripts call other scripts (PLEASE no): docker/makefile etc
- [ ] Bloated tools folder
- [x] Tests broken / do not exist
- [x] Whole dependency pipeline is very prone to exploding. Dependabot and stuff is nice and all but it is spammy and breaks things. Would like an approach similar to osu! repositories where they just do it manually when necessary. Ideally the action should detect changes on pipfile / pipfile.lock then re-pin all 4 files (similar to `make update`)
- [x] No CI (Added mypy)

**Comment by NiceAesth** [comment]
Feel free to take any of these tasks / discuss. Opening as this is getting to a point where it is a bit annoying to work with.

Also I want to mention that we should really consider caddy over nginx as well.

**Comment by minisbett** [comment]
#525
